// Based on intellij-markdown / sealed class pattern.
// Hand-written Kotlin — NOT generated by oxidtr.

data class Document(
    val blocks: List<Block>
)

sealed class Block

data class Heading(
    val level: Int,
    val inlines: List<Inline>
) : Block()

data class Paragraph(
    val inlines: List<Inline>
) : Block()

data class BlockQuote(
    val items: List<Block>
) : Block()

data class CodeBlock(
    val info: String?,
    val literal: String
) : Block()

data class HtmlBlock(
    val literal: String
) : Block()

data object ThematicBreak : Block()

data class ListBlock(
    val ordered: Boolean,
    val tight: Boolean,
    val start: Int?,
    val items: List<ListItem>
) : Block()

data class ListItem(
    val contents: List<Block>
) : Block()

sealed class Inline

data class Text(
    val literal: String
) : Inline()

data class CodeSpan(
    val literal: String
) : Inline()

data class Emphasis(
    val children: List<Inline>
) : Inline()

data class Strong(
    val children: List<Inline>
) : Inline()

data class Link(
    val destination: String,
    val title: String?,
    val children: List<Inline>
) : Inline()

data class Image(
    val destination: String,
    val title: String?,
    val children: List<Inline>
) : Inline()

data class HtmlInline(
    val literal: String
) : Inline()

data object SoftBreak : Inline()

data object LineBreak : Inline()
