// Based on pulldown-cmark's Tag/Event pattern.
// Hand-written Rust — NOT generated by oxidtr.

use std::collections::BTreeSet;

/// A CommonMark document is a sequence of block-level elements.
#[derive(Debug, Clone)]
pub struct Document {
    pub blocks: Vec<Block>,
}

/// Heading levels 1 through 6.
#[derive(Copy, Clone, Eq, PartialEq, Debug)]
pub enum HeadingLevel {
    H1 = 1,
    H2,
    H3,
    H4,
    H5,
    H6,
}

/// Block-level AST node.
#[derive(Debug, Clone)]
pub enum Block {
    /// ATX or Setext heading.
    Heading {
        level: HeadingLevel,
        inlines: Vec<Inline>,
    },
    /// A paragraph of inline content.
    Paragraph {
        inlines: Vec<Inline>,
    },
    /// A block quote; contains nested blocks.
    BlockQuote {
        items: Vec<Block>,
    },
    /// An indented or fenced code block.
    CodeBlock {
        info: Option<String>,
        literal: String,
    },
    /// Raw HTML block.
    HtmlBlock {
        literal: String,
    },
    /// Horizontal rule.
    ThematicBreak,
    /// Ordered or bullet list.
    ListBlock {
        ordered: bool,
        tight: bool,
        start: Option<i64>,
        items: Vec<ListItem>,
    },
    /// Single item in a list.
    ListItem {
        contents: Vec<Block>,
    },
}

/// Inline-level AST node.
#[derive(Debug, Clone)]
pub enum Inline {
    /// Plain text.
    Text(String),
    /// Inline code span.
    CodeSpan(String),
    /// Emphasized (italic) content.
    Emphasis(Vec<Inline>),
    /// Strong (bold) content.
    Strong(Vec<Inline>),
    /// Hyperlink.
    Link {
        destination: String,
        title: Option<String>,
        children: Vec<Inline>,
    },
    /// Embedded image.
    Image {
        destination: String,
        title: Option<String>,
        children: Vec<Inline>,
    },
    /// Raw inline HTML.
    HtmlInline(String),
    /// Soft line break (rendered as space).
    SoftBreak,
    /// Hard line break (rendered as <br>).
    LineBreak,
}
