// Based on commonmark-java's node class hierarchy pattern.
// Hand-written Java — NOT generated by oxidtr.

package org.commonmark.node;

import java.util.List;

/**
 * Base class for all CommonMark AST nodes.
 */
public abstract class Node {
    private Node parent;
    private Node firstChild;
    private Node lastChild;
    private Node prev;
    private Node next;

    public abstract void accept(Visitor visitor);

    public Node getParent() { return parent; }
    public Node getFirstChild() { return firstChild; }
    public Node getLastChild() { return lastChild; }
    public Node getNext() { return next; }
    public Node getPrevious() { return prev; }

    public void appendChild(Node child) {
        child.parent = this;
        if (lastChild != null) {
            lastChild.next = child;
            child.prev = lastChild;
            lastChild = child;
        } else {
            firstChild = child;
            lastChild = child;
        }
    }
}

/**
 * The root node of a CommonMark document.
 */
public class Document extends Block {
    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }
}

/**
 * Base class for block-level nodes.
 */
public abstract class Block extends Node {}

/**
 * An ATX or Setext heading.
 */
public class Heading extends Block {
    private int level;

    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }

    public int getLevel() { return level; }
    public void setLevel(int level) { this.level = level; }
}

/**
 * A paragraph of inline content.
 */
public class Paragraph extends Block {
    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }
}

/**
 * A block quote containing nested blocks.
 */
public class BlockQuote extends Block {
    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }
}

/**
 * A fenced or indented code block.
 */
public class CodeBlock extends Block {
    private String info;
    private String literal;

    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }

    public String getInfo() { return info; }
    public void setInfo(String info) { this.info = info; }
    public String getLiteral() { return literal; }
    public void setLiteral(String literal) { this.literal = literal; }
}

/**
 * A raw HTML block.
 */
public class HtmlBlock extends Block {
    private String literal;

    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }

    public String getLiteral() { return literal; }
    public void setLiteral(String literal) { this.literal = literal; }
}

/**
 * A horizontal rule (thematic break).
 */
public class ThematicBreak extends Block {
    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }
}

/**
 * An ordered or bullet list.
 */
public class ListBlock extends Block {
    private boolean ordered;
    private boolean tight;
    private Integer start;

    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }

    public boolean isOrdered() { return ordered; }
    public void setOrdered(boolean ordered) { this.ordered = ordered; }
    public boolean isTight() { return tight; }
    public void setTight(boolean tight) { this.tight = tight; }
    public Integer getStart() { return start; }
    public void setStart(Integer start) { this.start = start; }
}

/**
 * A single item in a list.
 */
public class ListItem extends Block {
    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }
}

/**
 * A run of plain text.
 */
public class Text extends Node {
    private String literal;

    public Text() {}
    public Text(String literal) { this.literal = literal; }

    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }

    public String getLiteral() { return literal; }
    public void setLiteral(String literal) { this.literal = literal; }
}

/**
 * An inline code span.
 */
public class CodeSpan extends Node {
    private String literal;

    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }

    public String getLiteral() { return literal; }
    public void setLiteral(String literal) { this.literal = literal; }
}

/**
 * Emphasized (italic) content.
 */
public class Emphasis extends Node {
    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }
}

/**
 * Strong (bold) content.
 */
public class Strong extends Node {
    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }
}

/**
 * A hyperlink.
 */
public class Link extends Node {
    private String destination;
    private String title;

    public Link() {}
    public Link(String destination, String title) {
        this.destination = destination;
        this.title = title;
    }

    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }

    public String getDestination() { return destination; }
    public void setDestination(String destination) { this.destination = destination; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
}

/**
 * An embedded image.
 */
public class Image extends Node {
    private String destination;
    private String title;

    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }

    public String getDestination() { return destination; }
    public void setDestination(String destination) { this.destination = destination; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
}

/**
 * Raw inline HTML.
 */
public class HtmlInline extends Node {
    private String literal;

    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }

    public String getLiteral() { return literal; }
    public void setLiteral(String literal) { this.literal = literal; }
}

/**
 * A soft line break (rendered as space).
 */
public class SoftBreak extends Node {
    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }
}

/**
 * A hard line break (rendered as &lt;br&gt;).
 */
public class LineBreak extends Node {
    @Override
    public void accept(Visitor visitor) { visitor.visit(this); }
}
