// Based on mdast (unified/syntax-tree) pattern.
// Hand-written TypeScript — NOT generated by oxidtr.

export interface Document {
  type: 'document';
  blocks: Block[];
}

export type Block =
  | Heading
  | Paragraph
  | BlockQuote
  | CodeBlock
  | HtmlBlock
  | ThematicBreak
  | ListBlock
  | ListItem;

export interface Heading {
  type: 'heading';
  level: number;
  inlines: Inline[];
}

export interface Paragraph {
  type: 'paragraph';
  inlines: Inline[];
}

export interface BlockQuote {
  type: 'blockquote';
  items: Block[];
}

export interface CodeBlock {
  type: 'code';
  info?: string;
  literal: string;
}

export interface HtmlBlock {
  type: 'html';
  literal: string;
}

export interface ThematicBreak {
  type: 'thematicBreak';
}

export interface ListBlock {
  type: 'list';
  ordered: boolean;
  tight: boolean;
  start?: number;
  items: ListItem[];
}

export interface ListItem {
  type: 'listItem';
  contents: Block[];
}

export type Inline =
  | Text
  | CodeSpan
  | Emphasis
  | Strong
  | Link
  | Image
  | HtmlInline
  | SoftBreak
  | LineBreak;

export interface Text {
  type: 'text';
  literal: string;
}

export interface CodeSpan {
  type: 'inlineCode';
  literal: string;
}

export interface Emphasis {
  type: 'emphasis';
  children: Inline[];
}

export interface Strong {
  type: 'strong';
  children: Inline[];
}

export interface Link {
  type: 'link';
  destination: string;
  title?: string;
  children: Inline[];
}

export interface Image {
  type: 'image';
  destination: string;
  title?: string;
  children: Inline[];
}

export interface HtmlInline {
  type: 'html';
  literal: string;
}

export interface SoftBreak {
  type: 'softBreak';
}

export interface LineBreak {
  type: 'break';
}
