// Based on goldmark's ast package pattern.
// Hand-written Go — NOT generated by oxidtr.

package ast

// Document is the root node of a Markdown document.
type Document struct {
	BaseBlock
	Blocks []Block
}

// Block is the interface for block-level nodes.
type Block interface {
	Node
	blockNode()
}

// Inline is the interface for inline-level nodes.
type Inline interface {
	Node
	inlineNode()
}

// Heading represents an ATX or Setext heading.
type Heading struct {
	BaseBlock
	// Level is a heading level between 1 and 6.
	Level   int
	Inlines []Inline
}

// Paragraph represents a paragraph of text.
type Paragraph struct {
	BaseBlock
	Inlines []Inline
}

// BlockQuote represents a block quote.
type BlockQuote struct {
	BaseBlock
	Items []Block
}

// CodeBlock represents an indented or fenced code block.
type CodeBlock struct {
	BaseBlock
	Info    string
	Literal string
}

// HtmlBlock represents a raw HTML block.
type HtmlBlock struct {
	BaseBlock
	Literal string
}

// ThematicBreak represents a horizontal rule.
type ThematicBreak struct {
	BaseBlock
}

// ListBlock represents an ordered or unordered list.
type ListBlock struct {
	BaseBlock
	Ordered bool
	Tight   bool
	Start   int
	Items   []ListItem
}

// ListItem represents a single item in a list.
type ListItem struct {
	BaseBlock
	Contents []Block
}

// Text represents a run of plain text.
type Text struct {
	BaseInline
	Literal string
}

// CodeSpan represents an inline code span.
type CodeSpan struct {
	BaseInline
	Literal string
}

// Emphasis represents emphasized (italic) text.
type Emphasis struct {
	BaseInline
	Children []Inline
}

// Strong represents strong (bold) text.
type Strong struct {
	BaseInline
	Children []Inline
}

// Link represents a hyperlink.
type Link struct {
	BaseInline
	Destination string
	Title       string
	Children    []Inline
}

// Image represents an embedded image.
type Image struct {
	BaseInline
	Destination string
	Title       string
	Children    []Inline
}

// HtmlInline represents raw inline HTML.
type HtmlInline struct {
	BaseInline
	Literal string
}

// SoftBreak represents a soft line break.
type SoftBreak struct {
	BaseInline
}

// LineBreak represents a hard line break.
type LineBreak struct {
	BaseInline
}
