// Based on Markdig's class hierarchy pattern.
// Hand-written C# — NOT generated by oxidtr.

using System.Collections.Generic;

public abstract class Block {}

public abstract class Inline {}

public class Document
{
    public List<Block> Blocks { get; set; }
}

public class Heading : Block
{
    public int Level { get; set; }
    public List<Inline> Inlines { get; set; }
}

public class Paragraph : Block
{
    public List<Inline> Inlines { get; set; }
}

public class BlockQuote : Block
{
    public List<Block> Items { get; set; }
}

public class CodeBlock : Block
{
    public string? Info { get; set; }
    public string Literal { get; set; }
}

public class HtmlBlock : Block
{
    public string Literal { get; set; }
}

public class ThematicBreak : Block {}

public class ListBlock : Block
{
    public bool Ordered { get; set; }
    public bool Tight { get; set; }
    public int? Start { get; set; }
    public List<ListItem> Items { get; set; }
}

public class ListItem : Block
{
    public List<Block> Contents { get; set; }
}

public class Text : Inline
{
    public string Literal { get; set; }
}

public class CodeSpan : Inline
{
    public string Literal { get; set; }
}

public class Emphasis : Inline
{
    public List<Inline> Children { get; set; }
}

public class Strong : Inline
{
    public List<Inline> Children { get; set; }
}

public class Link : Inline
{
    public string Destination { get; set; }
    public string? Title { get; set; }
    public List<Inline> Children { get; set; }
}

public class Image : Inline
{
    public string Destination { get; set; }
    public string? Title { get; set; }
    public List<Inline> Children { get; set; }
}

public class HtmlInline : Inline
{
    public string Literal { get; set; }
}

public class SoftBreak : Inline {}

public class LineBreak : Inline {}
