pub mod expr_translator;

use crate::backend::{GeneratedFile, TargetLang, is_native_type_alias, resolve_type};
use crate::ir::nodes::*;
use crate::parser::ast::{CompareOp, Multiplicity, SigMultiplicity};
use crate::analyze;
use std::collections::{HashMap, HashSet};
use std::fmt::Write;

pub fn generate(ir: &OxidtrIR) -> Vec<GeneratedFile> {
    let ctx = LeanContext::from_ir(ir);
    let mut files = Vec::new();

    files.push(GeneratedFile {
        path: "Types.lean".to_string(),
        content: generate_types(ir, &ctx),
    });

    if !ir.constraints.is_empty() {
        let constraints_content = generate_constraints(ir, &ctx);
        if !constraints_content.is_empty() {
            files.push(GeneratedFile {
                path: "Constraints.lean".to_string(),
                content: constraints_content,
            });
        }
    }

    if ir.operations.iter().any(|op| op.receiver_sig.is_none()) {
        files.push(GeneratedFile {
            path: "Operations.lean".to_string(),
            content: generate_operations(ir),
        });
    }

    files
}

// ── Context ──────────────────────────────────────────────────────────────────

struct LeanContext {
    children: HashMap<String, Vec<String>>,
    variant_names: HashSet<String>,
    struct_map: HashMap<String, StructureNode>,
    /// Parent fields: fields defined on the abstract sig that children inherit
    parent_fields: HashMap<String, Vec<IRField>>,
}

impl LeanContext {
    fn from_ir(ir: &OxidtrIR) -> Self {
        let mut children: HashMap<String, Vec<String>> = HashMap::new();
        for s in &ir.structures {
            if let Some(parent) = &s.parent {
                children.entry(parent.clone()).or_default().push(s.name.clone());
            }
        }
        let enum_parents: HashSet<String> = ir.structures.iter()
            .filter(|s| s.is_enum).map(|s| s.name.clone()).collect();
        let variant_names: HashSet<String> = ir.structures.iter()
            .filter(|s| s.parent.as_ref().map_or(false, |p| enum_parents.contains(p)))
            .map(|s| s.name.clone()).collect();
        let struct_map: HashMap<String, StructureNode> = ir.structures.iter()
            .map(|s| (s.name.clone(), s.clone()))
            .collect();

        // Collect parent fields for abstract sigs
        let mut parent_fields: HashMap<String, Vec<IRField>> = HashMap::new();
        for s in &ir.structures {
            if s.is_enum && !s.fields.is_empty() {
                parent_fields.insert(s.name.clone(), s.fields.clone());
            }
        }

        LeanContext { children, variant_names, struct_map, parent_fields }
    }

    fn is_variant(&self, name: &str) -> bool {
        self.variant_names.contains(name)
    }

    fn is_all_singleton_enum(&self, s: &StructureNode) -> bool {
        if !s.is_enum { return false; }
        let kids = match self.children.get(&s.name) {
            Some(v) => v,
            None => return false,
        };
        if kids.is_empty() { return false; }
        // All children have no fields AND parent has no fields
        if !s.fields.is_empty() { return false; }
        kids.iter().all(|name| {
            self.struct_map.get(name)
                .map_or(false, |cs| cs.fields.is_empty() && cs.sig_multiplicity == SigMultiplicity::One)
        })
    }
}

// ── Types.lean ──────────────────────────────────────────────────────────────

fn generate_types(ir: &OxidtrIR, ctx: &LeanContext) -> String {
    let mut out = String::new();
    writeln!(out, "-- Generated by oxidtr (Lean 4 backend)").unwrap();
    writeln!(out, "-- Mathlib imports (uncomment when proving theorems):").unwrap();
    writeln!(out, "-- import Mathlib.Data.List.Basic").unwrap();
    writeln!(out, "-- import Mathlib.Order.RelClasses").unwrap();
    writeln!(out).unwrap();

    for s in &ir.structures {
        if ctx.is_variant(&s.name) { continue; }
        if is_native_type_alias(&s.name) { continue; }

        let constraint_names = analyze::constraint_names_for_sig(ir, &s.name);
        if !constraint_names.is_empty() {
            writeln!(out, "-- Invariants:").unwrap();
            for cn in &constraint_names {
                writeln!(out, "-- - {cn}").unwrap();
            }
        }

        if s.is_enum {
            generate_inductive(&mut out, s, ir, ctx);
        } else {
            generate_structure(&mut out, s, ir, ctx);
        }
        writeln!(out).unwrap();
    }

    // Derived fields: receiver functions → Lean defs on the type
    generate_derived_fields(&mut out, ir);

    out
}

fn generate_structure(out: &mut String, s: &StructureNode, _ir: &OxidtrIR, ctx: &LeanContext) {
    if s.is_var {
        writeln!(out, "-- Alloy var sig: instances change across state transitions").unwrap();
    }

    writeln!(out, "structure {} where", s.name).unwrap();
    if s.fields.is_empty() {
        writeln!(out, "  mk ::").unwrap();
    } else {
        for f in &s.fields {
            if f.is_var {
                writeln!(out, "  -- Alloy var field: mutable across state transitions").unwrap();
            }
            let type_str = field_type_str(f, ctx);
            writeln!(out, "  {} : {}", expr_translator::to_lower_camel(&f.name), type_str).unwrap();
        }
    }
    writeln!(out, "  deriving Repr, BEq, DecidableEq").unwrap();

    // Singleton: generate instance
    if s.sig_multiplicity == SigMultiplicity::One {
        writeln!(out).unwrap();
        writeln!(out, "def {}Instance : {} :=", expr_translator::to_lower_camel(&s.name), s.name).unwrap();
        if s.fields.is_empty() {
            writeln!(out, "  {}.mk", s.name).unwrap();
        } else {
            // Generate concrete values: primitives get defaults, collections get empty
            let can_default = s.fields.iter().all(|f| {
                match f.mult {
                    Multiplicity::One => is_lean_defaultable(&f.target),
                    Multiplicity::Lone | Multiplicity::Set | Multiplicity::Seq => true,
                }
            });
            if can_default {
                write!(out, "  {{ ").unwrap();
                let field_inits: Vec<String> = s.fields.iter().map(|f| {
                    let val = match f.mult {
                        Multiplicity::One => lean_default_value(&f.target).to_string(),
                        Multiplicity::Lone => "none".to_string(),
                        Multiplicity::Set | Multiplicity::Seq => "[]".to_string(),
                    };
                    format!("{} := {}", expr_translator::to_lower_camel(&f.name), val)
                }).collect();
                write!(out, "{}", field_inits.join(", ")).unwrap();
                writeln!(out, " }}").unwrap();
            } else {
                writeln!(out, "  sorry -- provide concrete values").unwrap();
            }
        }
    }
}

fn generate_inductive(out: &mut String, s: &StructureNode, _ir: &OxidtrIR, ctx: &LeanContext) {
    let kids = ctx.children.get(&s.name);
    let kid_list = match kids {
        Some(v) => v.clone(),
        None => Vec::new(),
    };

    // Check if it's a simple enum (all singletons, no fields)
    let is_simple_enum = ctx.is_all_singleton_enum(s);

    // Get parent fields (fields on the abstract sig)
    let pfields = ctx.parent_fields.get(&s.name).cloned().unwrap_or_default();

    writeln!(out, "inductive {} where", s.name).unwrap();

    for kid_name in &kid_list {
        let variant_name = expr_translator::to_lower_camel(kid_name);
        if is_simple_enum {
            writeln!(out, "  | {} : {}", variant_name, s.name).unwrap();
        } else {
            // Collect fields: parent fields + variant-specific fields
            let kid_fields: Vec<&IRField> = if let Some(kid) = ctx.struct_map.get(kid_name) {
                pfields.iter().chain(kid.fields.iter()).collect()
            } else {
                pfields.iter().collect()
            };

            if kid_fields.is_empty() {
                writeln!(out, "  | {} : {}", variant_name, s.name).unwrap();
            } else {
                let named_params: Vec<String> = kid_fields.iter()
                    .map(|f| {
                        let fname = expr_translator::to_lower_camel(&f.name);
                        let ftype = field_type_str(f, ctx);
                        format!("({fname} : {ftype})")
                    })
                    .collect();
                writeln!(out, "  | {} {} : {}", variant_name, named_params.join(" "), s.name).unwrap();
            }
        }
    }
    writeln!(out, "  deriving Repr, BEq, DecidableEq").unwrap();
}

fn generate_derived_fields(out: &mut String, ir: &OxidtrIR) {
    for op in &ir.operations {
        if let Some(ref sig) = op.receiver_sig {
            let fn_name = expr_translator::to_lower_camel(&op.name);
            let params: Vec<String> = op.params.iter().map(|p| {
                let type_str = lean_type(&p.type_name, &p.mult);
                format!("({} : {type_str})", p.name)
            }).collect();
            let params_str = if params.is_empty() {
                String::new()
            } else {
                format!(" {}", params.join(" "))
            };

            let return_str = match &op.return_type {
                Some(rt) => lean_type(&rt.type_name, &rt.mult),
                None => "Bool".to_string(),
            };

            writeln!(out, "def {sig}.{fn_name} (self : {sig}){params_str} : {return_str} :=").unwrap();
            if !op.body.is_empty() {
                let body_expr = &op.body[op.body.len() - 1];
                let body_str = expr_translator::translate_with_ir(body_expr, ir);
                writeln!(out, "  {body_str}").unwrap();
            } else {
                writeln!(out, "  sorry -- oxidtr: implement {}", op.name).unwrap();
            }
            writeln!(out).unwrap();
        }
    }
}

fn field_type_str(f: &IRField, _ctx: &LeanContext) -> String {
    if let Some(vt) = &f.value_type {
        let resolved_key = resolve_type(TargetLang::Lean, &f.target);
        let resolved_val = resolve_type(TargetLang::Lean, vt);
        // Map type: Key → Value as List (Key × Value)
        return format!("List ({} × {})", resolved_key, resolved_val);
    }
    let resolved = resolve_type(TargetLang::Lean, &f.target);
    lean_mult_type(&resolved, &f.mult)
}

fn lean_mult_type(target: &str, mult: &Multiplicity) -> String {
    let lean_target = lean_primitive_type(target);
    match mult {
        Multiplicity::One => lean_target,
        Multiplicity::Lone => format!("Option {lean_target}"),
        Multiplicity::Set => format!("List {lean_target}"),
        Multiplicity::Seq => format!("List {lean_target}"),
    }
}

fn lean_type(type_name: &str, mult: &Multiplicity) -> String {
    lean_mult_type(type_name, mult)
}

fn is_lean_defaultable(name: &str) -> bool {
    matches!(name, "Int" | "String" | "Bool" | "Nat")
}

fn lean_default_value(name: &str) -> &str {
    match name {
        "Int" => "0",
        "Nat" => "0",
        "String" => "\"\"",
        "Bool" => "false",
        _ => "sorry",
    }
}

fn lean_primitive_type(name: &str) -> String {
    match name {
        "Int" => "Int".to_string(),
        "String" => "String".to_string(),
        "Bool" => "Bool".to_string(),
        other => other.to_string(),
    }
}

// ── Constraints.lean ────────────────────────────────────────────────────────

fn generate_constraints(ir: &OxidtrIR, _ctx: &LeanContext) -> String {
    let sig_constraints = analyze::analyze(ir);
    if sig_constraints.is_empty() && ir.properties.is_empty() {
        return String::new();
    }

    let mut out = String::new();
    writeln!(out, "-- Generated by oxidtr (Lean 4 backend)").unwrap();
    writeln!(out, "-- Constraint theorems with proof strategies").unwrap();
    writeln!(out, "-- Mathlib imports (uncomment when proving):").unwrap();
    writeln!(out, "-- import Mathlib.Data.List.Basic").unwrap();
    writeln!(out, "-- import Mathlib.Order.RelClasses").unwrap();
    writeln!(out, "import Types").unwrap();
    writeln!(out).unwrap();

    let mut theorem_idx = 0;

    for c in &sig_constraints {
        match c {
            analyze::ConstraintInfo::NoSelfRef { sig_name, field_name } => {
                let fname = expr_translator::to_lower_camel(field_name);
                writeln!(out, "theorem no_self_ref_{sig_name}_{field_name} :").unwrap();
                writeln!(out, "    ∀ (x : {sig_name}), x.{fname} ≠ some x := by").unwrap();
                writeln!(out, "  intro x").unwrap();
                writeln!(out, "  sorry -- Needs: subtype encoding or refinement type").unwrap();
                writeln!(out).unwrap();
                theorem_idx += 1;
            }
            analyze::ConstraintInfo::Acyclic { sig_name, field_name } => {
                let fname = expr_translator::to_lower_camel(field_name);
                writeln!(out, "theorem acyclic_{sig_name}_{field_name} :").unwrap();
                writeln!(out, "    ∀ (x : {sig_name}), ¬ Relation.TransGen (fun a b => a.{fname} = some b) x x := by").unwrap();
                writeln!(out, "  intro x h").unwrap();
                writeln!(out, "  sorry -- Needs: well-founded recursion on Relation.TransGen").unwrap();
                writeln!(out).unwrap();
                theorem_idx += 1;
            }
            analyze::ConstraintInfo::FieldOrdering { sig_name, left_field, op, right_field } => {
                let lf = expr_translator::to_lower_camel(left_field);
                let rf = expr_translator::to_lower_camel(right_field);
                let lean_op = match op {
                    CompareOp::Lt => "<",
                    CompareOp::Gt => ">",
                    CompareOp::Lte => "≤",
                    CompareOp::Gte => "≥",
                    CompareOp::Eq => "=",
                    CompareOp::NotEq => "≠",
                    _ => "?",
                };
                writeln!(out, "theorem field_ordering_{sig_name}_{left_field}_{right_field} :").unwrap();
                writeln!(out, "    ∀ (x : {sig_name}), x.{lf} {lean_op} x.{rf} := by").unwrap();
                writeln!(out, "  intro x").unwrap();
                writeln!(out, "  omega").unwrap();
                writeln!(out).unwrap();
                theorem_idx += 1;
            }
            analyze::ConstraintInfo::Implication { sig_name, condition, consequent } => {
                let cond_str = expr_translator::translate_with_ir(condition, ir);
                let cons_str = expr_translator::translate_with_ir(consequent, ir);
                writeln!(out, "theorem implication_{sig_name}_{theorem_idx} :").unwrap();
                writeln!(out, "    ∀ (x : {sig_name}), {cond_str} → {cons_str} := by").unwrap();
                writeln!(out, "  intro x h").unwrap();
                writeln!(out, "  sorry -- Hint: derive consequent from hypothesis h").unwrap();
                writeln!(out).unwrap();
                theorem_idx += 1;
            }
            analyze::ConstraintInfo::Iff { sig_name, left, right } => {
                let left_str = expr_translator::translate_with_ir(left, ir);
                let right_str = expr_translator::translate_with_ir(right, ir);
                writeln!(out, "theorem iff_{sig_name}_{theorem_idx} :").unwrap();
                writeln!(out, "    ∀ (x : {sig_name}), {left_str} ↔ {right_str} := by").unwrap();
                writeln!(out, "  intro x").unwrap();
                writeln!(out, "  constructor").unwrap();
                writeln!(out, "  · intro h; sorry -- forward direction").unwrap();
                writeln!(out, "  · intro h; sorry -- backward direction").unwrap();
                writeln!(out).unwrap();
                theorem_idx += 1;
            }
            analyze::ConstraintInfo::Prohibition { sig_name, condition } => {
                let cond_str = expr_translator::translate_with_ir(condition, ir);
                writeln!(out, "theorem prohibition_{sig_name}_{theorem_idx} :").unwrap();
                writeln!(out, "    ∀ (x : {sig_name}), ¬({cond_str}) := by").unwrap();
                writeln!(out, "  intro x h").unwrap();
                writeln!(out, "  sorry -- Hint: derive contradiction from h").unwrap();
                writeln!(out).unwrap();
                theorem_idx += 1;
            }
            analyze::ConstraintInfo::Disjoint { sig_name, left, right } => {
                writeln!(out, "theorem disjoint_{sig_name}_{theorem_idx} :").unwrap();
                writeln!(out, "    ∀ (x : {sig_name}), ¬(x ∈ {left} ∧ x ∈ {right}) := by").unwrap();
                writeln!(out, "  intro x ⟨h₁, h₂⟩").unwrap();
                writeln!(out, "  sorry -- Hint: derive contradiction from h₁ and h₂").unwrap();
                writeln!(out).unwrap();
                theorem_idx += 1;
            }
            analyze::ConstraintInfo::Exhaustive { sig_name, categories } => {
                let cats = categories.iter()
                    .map(|c| format!("x ∈ {c}"))
                    .collect::<Vec<_>>()
                    .join(" ∨ ");
                writeln!(out, "theorem exhaustive_{sig_name}_{theorem_idx} :").unwrap();
                writeln!(out, "    ∀ (x : {sig_name}), {cats} := by").unwrap();
                writeln!(out, "  intro x").unwrap();
                writeln!(out, "  cases x <;> simp").unwrap();
                writeln!(out).unwrap();
                theorem_idx += 1;
            }
            analyze::ConstraintInfo::CardinalityBound { sig_name, field_name, bound } => {
                let fname = expr_translator::to_lower_camel(field_name);
                let bound_str = match bound {
                    analyze::BoundKind::Exact(n) => format!("x.{fname}.length = {n}"),
                    analyze::BoundKind::AtMost(n) => format!("x.{fname}.length ≤ {n}"),
                    analyze::BoundKind::AtLeast(n) => format!("x.{fname}.length ≥ {n}"),
                };
                writeln!(out, "theorem cardinality_{sig_name}_{field_name} :").unwrap();
                writeln!(out, "    ∀ (x : {sig_name}), {bound_str} := by").unwrap();
                writeln!(out, "  intro x").unwrap();
                writeln!(out, "  simp [List.length]").unwrap();
                writeln!(out, "  omega").unwrap();
                writeln!(out).unwrap();
                theorem_idx += 1;
            }
            // Presence: type-guaranteed in Lean (non-Option = required)
            analyze::ConstraintInfo::Presence { sig_name, field_name, kind } => {
                let fname = expr_translator::to_lower_camel(field_name);
                match kind {
                    analyze::PresenceKind::Required => {
                        writeln!(out, "-- {sig_name}.{fname}: required (guaranteed by type — field is non-Option)").unwrap();
                    }
                    analyze::PresenceKind::Absent => {
                        writeln!(out, "-- {sig_name}.{fname}: absent (guaranteed by type — field not present)").unwrap();
                    }
                }
                writeln!(out).unwrap();
            }
            // Membership, Named — skip
            _ => {}
        }
    }

    // Emit fact name anchors so `check` validation can find them
    writeln!(out, "-- Validated facts:").unwrap();
    for c in &ir.constraints {
        if let Some(ref name) = c.name {
            writeln!(out, "-- {name}").unwrap();
        }
    }
    writeln!(out).unwrap();

    // Properties (asserts) as theorems
    for p in &ir.properties {
        let body_str = expr_translator::translate_with_ir(&p.expr, ir);
        writeln!(out, "theorem {} :", p.name).unwrap();
        writeln!(out, "    {body_str} := by").unwrap();
        writeln!(out, "  sorry").unwrap();
        writeln!(out).unwrap();
    }

    out
}

// ── Operations.lean ─────────────────────────────────────────────────────────

fn generate_operations(ir: &OxidtrIR) -> String {
    let mut out = String::new();
    writeln!(out, "-- Generated by oxidtr (Lean 4 backend)").unwrap();
    writeln!(out, "import Types").unwrap();
    writeln!(out).unwrap();

    for op in &ir.operations {
        // Skip receiver-based ops (derived fields) — those go in Types.lean
        if op.receiver_sig.is_some() { continue; }

        let fn_name = expr_translator::to_lower_camel(&op.name);
        let params: Vec<String> = op.params.iter().map(|p| {
            let type_str = lean_type(&p.type_name, &p.mult);
            format!("({} : {type_str})", p.name)
        }).collect();
        let params_str = params.join(" ");

        let return_str = match &op.return_type {
            Some(rt) => lean_type(&rt.type_name, &rt.mult),
            None => "Bool".to_string(),
        };

        writeln!(out, "def {fn_name} {params_str} : {return_str} :=").unwrap();
        if !op.body.is_empty() {
            let body_expr = &op.body[op.body.len() - 1];
            let body_str = expr_translator::translate_with_ir(body_expr, ir);
            writeln!(out, "  {body_str}").unwrap();
        } else {
            writeln!(out, "  sorry -- oxidtr: implement {}", op.name).unwrap();
        }
        writeln!(out).unwrap();
    }

    out
}
