// Based on swift-markdown's enum + struct pattern.
// Hand-written Swift — NOT generated by oxidtr.

struct Document {
    let blocks: [Block]
}

enum Block {
    case heading(level: Int, inlines: [Inline])
    case paragraph(inlines: [Inline])
    case blockQuote(items: [Block])
    case codeBlock(info: String?, literal: String)
    case htmlBlock(literal: String)
    case thematicBreak
    case listBlock(ordered: Bool, tight: Bool, start: Int?, items: [ListItem])
    case listItem(contents: [Block])
}

struct ListItem {
    let contents: [Block]
}

enum Inline {
    case text(literal: String)
    case codeSpan(literal: String)
    case emphasis(children: [Inline])
    case strong(children: [Inline])
    case link(destination: String, title: String?, children: [Inline])
    case image(destination: String, title: String?, children: [Inline])
    case htmlInline(literal: String)
    case softBreak
    case lineBreak
}
